# Testa diverse saker
- Kolla hur hx_plac har blivit felaktiga
- Undersök CV med trav-data i syfte att kunna använda testdata

In [1]:
import pandas as pd
import numpy as np
import fixa_features as ff
import fixa_mer_features as ff2

## Kollar hur hx_plac är felaktiga. Jämför värden med hx_dat med de verkliga i datum

In [2]:
df=pd.read_csv('mer_komplett.csv')

In [3]:
# df.drop('Unnamed: 0',axis=1,inplace=True)
# df.drop('Unnamed: 0.1',axis=1,inplace=True)
print(df.shape)
df.drop_duplicates(['datum','häst'],inplace=True)
df.sort_values(by=['datum','bana','avd'],inplace=True)
df.reset_index(drop=True,inplace=True)
print(df.shape)

df.info()

(37788, 78)
(37788, 78)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37788 entries, 0 to 37787
Data columns (total 78 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   datum      37788 non-null  object
 1   avd        37788 non-null  int64
 2   häst       37788 non-null  object
 3   bana       37788 non-null  object
 4   dist       37788 non-null  int64
 5   h1_bana    37788 non-null  object
 6   h1_dat     37788 non-null  object
 7   h1_dist    37788 non-null  float64
 8   h1_kmtid   37788 non-null  float64
 9   h1_kusk    37788 non-null  object
 10  h1_odds    4974 non-null   float64
 11  h1_plac    37788 non-null  float64
 12  h1_pris    34701 non-null  float64
 13  h1_spår    34970 non-null  float64
 14  h2_bana    37788 non-null  object
 15  h2_dat     37788 non-null  object
 16  h2_dist    37788 non-null  float64
 17  h2_kmtid   37788 non-null  float64
 18  h2_kusk    37788 non-null  object
 19  h2_odds    4988 non-null   float64
 20  h2_plac    37788 non-null  float64
 21  h2_pris    34208 non-null  float64
 22  h2_spår    34970 non-null  float64
 23  h3_bana    37788 non-null  object
 24  h3_dat     37788 non-null  object
 25  h3_dist    37788 non-null  float64
 26  h3_kmtid   37788 non-null  float64
 27  h3_kusk    37788 non-null  object
 28  h3_odds    4981 non-null   float64
 29  h3_plac    37788 non-null  float64
 30  h3_pris    33826 non-null  float64
 31  h3_spår    34970 non-null  float64
 32  h4_bana    37788 non-null  object
 33  h4_dat     37788 non-null  object
 34  h4_dist    37788 non-null  float64
 35  h4_kmtid   37788 non-null  float64
 36  h4_kusk    37788 non-null  object
 37  h4_odds    4966 non-null   float64
 38  h4_plac    37788 non-null  float64
 39  h4_pris    33486 non-null  float64
 40  h4_spår    34970 non-null  float64
 41  h5_bana    37788 non-null  object
 42  h5_dat     37788 non-null  object
 43  h5_dist    37788 non-null  float64
 44  h5_kmtid   37788 non-null  float64
 45  h5_kusk    37788 non-null  object
 46  h5_odds    4949 non-null   float64
 47  h5_plac    37788 non-null  float64
 48  h5_pris    33132 non-null  float64
 49  h5_spår    34970 non-null  float64
 50  kr         37788 non-null  float64
 51  kusk       37788 non-null  object
 52  kön        37788 non-null  object
 53  lopp_dist  5020 non-null   float64
 54  plac       37788 non-null  float64
 55  podds      5020 non-null   float64
 56  pris       37788 non-null  float64
 57  spår       37699 non-null  float64
 58  start      37788 non-null  int64
 59  streck     37647 non-null  float64
 60  vodds      5020 non-null   float64
 61  ålder      37788 non-null  int64
 62  bins       37788 non-null  int64
 63  h1_auto    37753 non-null  float64
 64  h2_auto    37788 non-null  float64
 65  h3_auto    37788 non-null  float64
 66  h4_auto    37788 non-null  float64
 67  h5_auto    37788 non-null  float64
 68  h1_perf    34701 non-null  float64
 69  h2_perf    34208 non-null  float64
 70  h3_perf    33826 non-null  float64
 71  h4_perf    33486 non-null  float64
 72  h5_perf    33132 non-null  float64
 73  senast     37788 non-null  object
 74  delta1     37788 non-null  object
 75  delta2     37788 non-null  object
 76  delta3     37788 non-null  object
 77  delta4     37788 non-null  object
dtypes: float64(48), int64(5), object(25)
memory usage: 22.5+ MB

In [4]:
df.to_csv('mer_komplett.csv',index=False)

In [5]:
df.h1_plac.unique()

array([ 1., 14.,  5.,  2., 13.,  4.,  3.,  6.,  7.,  8., 11., 10.,  9.,
       12.,  0.])

In [6]:
df.datum=pd.to_datetime(df.datum)

In [23]:
hx='h1_dat'
# df[hx]=df[hx].str.replace('(','',regex=False)
# df[hx]=df[hx].str.replace(')','',regex=False)
df[hx]=pd.to_datetime(df[hx])

In [24]:
df[['h1_dat','h2_dat','h3_dat','h4_dat','h5_dat']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37788 entries, 0 to 37787
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   h1_dat  37788 non-null  datetime64[ns]
 1   h2_dat  37788 non-null  datetime64[ns]
 2   h3_dat  37788 non-null  datetime64[ns]
 3   h4_dat  37788 non-null  datetime64[ns]
 4   h5_dat  37788 non-null  datetime64[ns]
dtypes: datetime64[ns](5)
memory usage: 1.4 MB

83

0          2 days
1          2 days
2          2 days
3          2 days
4          2 days
           ...
37819   2249 days
37820   2249 days
37821   2249 days
37822   2249 days
37823   2249 days
Name: datum, Length: 37824, dtype: timedelta64[ns]

In [25]:
# df[['h1_dat','h1_spår','h1_pris']][df.datum=='2015-01-03'].head(50)
# pd.to_datetime(df.h1_dat, format="%y%m%d")
df['senast']=df.datum - df.h1_dat
df['timestamp']=df.datum-pd.to_datetime('2015-01-01')

df[['datum','timestamp','senast','häst','streck','h1_dat','h1_bana','h1_pris','h1_kmtid']]

,datum,timestamp,senast,häst,streck,h1_dat,h1_bana,h1_pris,h1_kmtid
0,2015-01-03,2 days,14 days,ALFA GIACOMO,1.0,2014-12-20,Åby,100.0,16.1
1,2015-01-03,2 days,19 days,CALVIN BOREL,67.0,2014-12-15,Halmstad,35.0,13.3
2,2015-01-03,2 days,8 days,ELEGANCE BRODDE,1.0,2014-12-26,Solvalla,200.0,15.7
3,2015-01-03,2 days,14 days,KAMANDA,8.0,2014-12-20,Åby,100.0,13.7
4,2015-01-03,2 days,35 days,MAN WINNER,0.0,2014-11-29,Jägersro,100.0,12.0
...,...,...,...,...,...,...,...,...,...
37783,2021-03-06,2256 days,14 days,EXCLUSIVE MATTER,12.0,2021-02-20,Mantorp,110.0,17.6
37784,2021-03-06,2256 days,14 days,SWEETMAN,11.0,2021-02-20,Mantorp,110.0,23.9
37785,2021-03-06,2256 days,28 days,CARGO DOOR,8.0,2021-02-06,Solvalla,220.0,14.1
37786,2021-03-06,2256 days,16 days,ECHELON,4.0,2021-02-18,Åby,35.0,14.5
37787,2021-03-06,2256 days,24 days,HURRICANE RIVER,1.0,2021-02-10,Jägersro,60.0,13.0

In [26]:


# df.h1_pris = df.h1_pris.str.replace("'","")
# df.h2_pris = df.h2_pris.str.replace("'","")
# df.h3_pris = df.h3_pris.str.replace("'","")
# df.h4_pris = df.h4_pris.str.replace("'","")
# df.h5_pris = df.h5_pris.str.replace("'","")
df.h1_pris = df.h1_pris.astype('float')
df.h2_pris = df.h2_pris.astype('float')
df.h3_pris = df.h3_pris.astype('float')
df.h4_pris = df.h4_pris.astype('float')
df.h5_pris = df.h5_pris.astype('float')

In [27]:
df[['h1_plac','h2_plac','h3_plac','h4_plac','h5_plac','h1_pris','h2_pris','h3_pris','h4_pris','h5_pris']]

,h1_plac,h2_plac,h3_plac,h4_plac,h5_plac,h1_pris,h2_pris,h3_pris,h4_pris,h5_pris
0,1.0,1.0,1.0,13.0,5.0,100.0,20.0,25.0,30.0,30.0
1,14.0,13.0,14.0,14.0,14.0,35.0,NaN,20.0,100.0,100.0
2,5.0,13.0,5.0,2.0,5.0,200.0,100.0,100.0,100.0,100.0
3,1.0,3.0,1.0,13.0,2.0,100.0,30.0,30.0,100.0,30.0
4,2.0,5.0,2.0,3.0,13.0,100.0,200.0,100.0,30.0,30.0
...,...,...,...,...,...,...,...,...,...,...
37783,6.0,2.0,4.0,1.0,0.0,110.0,150.0,60.0,25.0,110.0
37784,0.0,1.0,0.0,2.0,5.0,110.0,220.0,220.0,110.0,110.0
37785,6.0,1.0,7.0,1.0,7.0,220.0,110.0,220.0,110.0,110.0
37786,3.0,1.0,5.0,7.0,1.0,35.0,60.0,40.0,110.0,60.0
37787,4.0,1.0,2.0,0.0,3.0,60.0,35.0,60.0,110.0,50.0

In [30]:
df.h1_plac.unique()

array([ 1., 14.,  5.,  2., 13.,  4.,  3.,  6.,  7.,  8., 11., 10.,  9.,
       12.,  0.])

In [249]:
# df.h1_plac=df.h1_plac.str.replace('r','',regex=False)
# df.h2_plac=df.h2_plac.str.replace('r','',regex=False)
# df.h3_plac=df.h3_plac.str.replace('r','',regex=False)
# df.h4_plac=df.h4_plac.str.replace('r','',regex=False)
# df.h5_plac=df.h5_plac.str.replace('r','',regex=False)

In [250]:
# df.h1_plac = df.h1_plac.str.replace('.0','',regex=False)
# df.h2_plac = df.h2_plac.str.replace('.0','',regex=False)
# df.h3_plac = df.h3_plac.str.replace('.0','',regex=False)
# df.h4_plac = df.h4_plac.str.replace('.0','',regex=False)
# df.h5_plac = df.h5_plac.str.replace('.0','',regex=False)
# df.plac = df.plac.str.replace('.0','',regex=False)

In [32]:
temp_df=df[['datum','bana','avd','häst','plac','h1_dat','h1_plac','h2_dat','h2_plac','h3_dat','h3_plac']]

In [33]:
cnt=0
felHist_df = pd.DataFrame(columns=['datum','bana','avd','häst','plac','h1_dat','h1_plac'])
for d in temp_df.values:
    r1=df[(df.datum==d[5]) & (df.häst==d[3]) & (df.plac != d[6])]
    r2=df[(df.datum==d[7]) & (df.häst==d[3]) & (df.plac != d[8])]
    r3=df[(df.datum==d[9]) & (df.häst==d[3]) & (df.plac != d[10])]
    if r1.size==0 and r2.size==0 and r3.size==0:
        continue
    # print(f'r1dat={r1.datum} r1h1dat={d[3]} r1plac={r1.plac} r1h1plac={d[4]}')
    # print(r1.datum,d[0],d[3])
    
    felHist_df.loc[felHist_df.shape[0]] = d[0:7]
    cnt+=1
    if cnt%500==0:
        print(cnt)
print(felHist_df.shape[0], cnt)

500
1000
1500
2000
2500
3000
3500
4000
4500
5000
5500
6000
6500
7000
7500
8000
8500
9000
9500
10000
10500
11000
11500
12000
12500
13000
13500
14000
14500
15000
15500
16000
16500
17000
17500
17835 17835

In [39]:
felHist_df.drop_duplicates(['datum','bana','avd','häst']).shape
felHist_df.to_csv('felaktigHist.csv',index=False,date_format='%s')
felHist_df

           datum bana avd               häst  plac     h1_dat  h1_plac
0     2015-01-17  ÅBY   1         RAMBO FLEX   0.0 2015-01-03     13.0
1     2015-01-17  ÅBY   1  VÄSTERBOONTHENEWS   1.0 2015-01-03      2.0
2     2015-01-17  ÅBY   2     RAYMOND PALEMA   0.0 2015-01-10      4.0
3     2015-01-17  ÅBY   2     SHARIF AMERICA   0.0 2015-01-03     13.0
4     2015-01-17  ÅBY   2         SPRINGOVER   1.0 2015-01-03      2.0
...          ...  ...  ..                ...   ...        ...      ...
17830 2021-03-06  ÅBY   7         UPPER FACE   2.0 2021-02-13      4.0
17831 2021-03-06  ÅBY   7     CALL ME BRODDA   4.0 2021-02-20      1.0
17832 2021-03-06  ÅBY   7       LOVE HÅLERYD   6.0 2021-02-20      0.0
17833 2021-03-06  ÅBY   7   EXCLUSIVE MATTER   8.0 2021-02-20      6.0
17834 2021-03-06  ÅBY   7         CARGO DOOR   0.0 2021-02-06      6.0

[17835 rows x 7 columns]

In [35]:
# felHist_df = pd.read_csv('felaktigHist.csv',index=False)
felHist_df.datum
#felHist_df.datum.dt.strftime("%y-%m-%d")

0       2015-01-17
1       2015-01-17
2       2015-01-17
3       2015-01-17
4       2015-01-17
           ...
17830   2021-03-06
17831   2021-03-06
17832   2021-03-06
17833   2021-03-06
17834   2021-03-06
Name: datum, Length: 17835, dtype: datetime64[ns]

In [36]:
felHist_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17835 entries, 0 to 17834
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   datum    17835 non-null  datetime64[ns]
 1   bana     17835 non-null  object
 2   avd      17835 non-null  object
 3   häst     17835 non-null  object
 4   plac     17835 non-null  float64
 5   h1_dat   17835 non-null  datetime64[ns]
 6   h1_plac  17835 non-null  float64
dtypes: datetime64[ns](2), float64(2), object(3)
memory usage: 1.1+ MB

In [37]:
felHist_df.plac.unique()

array([ 0.,  1.,  5.,  6.,  8.,  3.,  7.,  4., 13.,  2.])

In [38]:
df

,datum,avd,häst,bana,dist,h1_bana,h1_dat,h1_dist,h1_kmtid,h1_kusk,...,h2_perf,h3_perf,h4_perf,h5_perf,senast,delta1,delta2,delta3,delta4,timestamp
0,2015-01-03,1,ALFA GIACOMO,JÄGERSRO,2140,Åby,2014-12-20,2640.0,16.1,Johan Untersteiner,...,4904.292577,5483.165792,14.888643,812.892351,14 days,18 days,10 days,78 days,21 days,2 days
1,2015-01-03,1,CALVIN BOREL,JÄGERSRO,2140,Halmstad,2014-12-15,2140.0,13.3,Conrad Lugauer,...,NaN,7.373306,16.487213,16.487213,19 days,13 days,7 days,31 days,14 days,2 days
2,2015-01-03,1,ELEGANCE BRODDE,JÄGERSRO,2140,Solvalla,2014-12-26,2140.0,15.7,Torbjörn Jansson,...,27.182818,1484.131591,6651.416330,1484.131591,8 days,20 days,7 days,21 days,14 days,2 days
3,2015-01-03,1,KAMANDA,JÄGERSRO,2140,Åby,2014-12-20,2140.0,13.7,Bernardo Grasso,...,2209.670505,6006.507182,27.182818,3643.130764,14 days,21 days,25 days,24 days,12 days,2 days
4,2015-01-03,1,MAN WINNER,JÄGERSRO,2140,Jägersro,2014-11-29,1640.0,12.0,Thomas Uhrberg,...,2098.879024,6651.416330,2209.670505,14.888643,35 days,14 days,21 days,7 days,24 days,2 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37783,2021-03-06,7,EXCLUSIVE MATTER,ÅBY,1640,Mantorp,2021-02-20,2140.0,17.6,Stefan Persson,...,8146.288038,1895.375557,5483.165792,18962.908821,14 days,7 days,10 days,13 days,33 days,2256 days
37784,2021-03-06,7,SWEETMAN,ÅBY,1640,Mantorp,2021-02-20,2140.0,23.9,Erik Adielsson,...,16265.698341,26817.602837,6976.064300,1556.570345,14 days,14 days,42 days,7 days,14 days,2256 days
37785,2021-03-06,7,CARGO DOOR,ÅBY,1640,Solvalla,2021-02-06,2140.0,14.1,Magnus A Djuse,...,11501.585598,809.821435,11501.585598,572.630228,28 days,21 days,49 days,21 days,14 days,2256 days
37786,2021-03-06,7,ECHELON,ÅBY,1640,Åby,2021-02-18,1640.0,14.5,Victor Rosleff,...,8494.483919,938.647235,572.630228,8494.483919,16 days,15 days,9 days,51 days,10 days,2256 days
37787,2021-03-06,7,HURRICANE RIVER,ÅBY,1640,Jägersro,2021-02-10,1640.0,13.0,Thomas Uhrberg,...,6487.769258,5152.164935,18962.908821,2852.672356,24 days,5 days,9 days,11 days,10 days,2256 days

# Kolla hur man kan ancända CV för Trav-data i syfte att kunna köra learn med både train och test data

In [257]:
import pandas as pd
import numpy as np
import fixa_features as ff
import fixa_mer_features as ff2

# df=pd.read_csv('mer_komplett.csv')
df.drop('tid',axis=1,inplace=True)

df=ff2.fixa_mer_features(df,hist=False)
df.lopp_dist=df.lopp_dist.astype('float')
df.plac = (df.plac==1)*1
print(df.plac.value_counts())  # CatBoost fungerar bättre med 0,1 än False, True
print(df.start.value_counts())

(37824, 64)
fixa features start (37824, 64)
efter fixa_features (37824, 65)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 37824 entries, 0 to 37823
Data columns (total 65 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   datum      37824 non-null  datetime64[ns]
 1   avd        37824 non-null  int64
 2   häst       37824 non-null  object
 3   bana       37824 non-null  object
 4   dist       37824 non-null  int64
 5   h1_bana    37824 non-null  object
 6   h1_dat     37824 non-null  datetime64[ns]
 7   h1_dist    37824 non-null  float64
 8   h1_kmtid   37820 non-null  object
 9   h1_kusk    37824 non-null  object
 10  h1_odds    37771 non-null  object
 11  h1_plac    37817 non-null  object
 12  h1_pris    34738 non-null  float64
 13  h1_spår    35008 non-null  float64
 14  h2_bana    37824 non-null  object
 15  h2_dat     37824 non-null  datetime64[ns]
 16  h2_dist    37824 non-null  float64
 17  h2_kmtid   37821 non-null  object
 18  h2_kusk    37824 non-null  object
 19  h2_odds    37801 non-null  object
 20  h2_plac    37823 non-null  object
 21  h2_pris    34227 non-null  float64
 22  h2_spår    34611 non-null  float64
 23  h3_bana    37818 non-null  object
 24  h3_dat     37818 non-null  datetime64[ns]
 25  h3_dist    37818 non-null  float64
 26  h3_kmtid   37814 non-null  object
 27  h3_kusk    37818 non-null  object
 28  h3_odds    37793 non-null  object
 29  h3_plac    37817 non-null  object
 30  h3_pris    33832 non-null  float64
 31  h3_spår    34272 non-null  float64
 32  h4_bana    37796 non-null  object
 33  h4_dat     37796 non-null  datetime64[ns]
 34  h4_dist    37796 non-null  float64
 35  h4_kmtid   37792 non-null  object
 36  h4_kusk    37796 non-null  object
 37  h4_odds    37756 non-null  object
 38  h4_plac    37796 non-null  object
 39  h4_pris    33447 non-null  float64
 40  h4_spår    34001 non-null  float64
 41  h5_bana    37741 non-null  object
 42  h5_dat     37741 non-null  datetime64[ns]
 43  h5_dist    37741 non-null  float64
 44  h5_kmtid   37733 non-null  object
 45  h5_kusk    37741 non-null  object
 46  h5_odds    37696 non-null  object
 47  h5_plac    37739 non-null  object
 48  h5_pris    33095 non-null  float64
 49  h5_spår    33750 non-null  float64
 50  kr         37824 non-null  object
 51  kusk       37824 non-null  object
 52  kön        37824 non-null  object
 53  lopp_dist  37824 non-null  object
 54  plac       37824 non-null  float64
 55  podds      37824 non-null  float64
 56  pris       37824 non-null  float64
 57  spår       37824 non-null  int32
 58  start      37824 non-null  int64
 59  streck     37740 non-null  object
 60  vodds      37824 non-null  float64
 61  ålder      37824 non-null  int64
 62  senast     37824 non-null  timedelta64[ns]
 63  timestamp  37824 non-null  timedelta64[ns]
 64  bins       37824 non-null  int64
dtypes: datetime64[ns](6), float64(19), int32(1), int64(5), object(32), timedelta64[ns](2)
memory usage: 18.9+ MB
None
bana 0
kusk 0
avd 0
spår==0            datum            bana  avd              häst  spår  start  vodds
20423 2018-05-13  CHARLOTTENLUND    1       GREECE BOKO     0      0  66.06
20427 2018-05-13  CHARLOTTENLUND    1     UNCERTAIN AGE     0      0   7.84
20431 2018-05-13  CHARLOTTENLUND    2  EXCLAMATION MARK     0      0  11.93
20434 2018-05-13  CHARLOTTENLUND    2      RAKET BRODDE     0      0   4.05
20435 2018-05-13  CHARLOTTENLUND    2     TWITTER LASER     0      0  10.03
...          ...             ...  ...               ...   ...    ...    ...
24902 2018-12-28           ÅRHUS    7    A'KA SJÆL SKOV     0      0  72.75
24903 2018-12-28           ÅRHUS    7     BELLA HØJGÅRD     0      0  44.31
24904 2018-12-28           ÅRHUS    7     DAMIEN SHADOW     0      0  52.32
24905 2018-12-28           ÅRHUS    7       DEKADENT K.     0      0  32.40
24913 2018-12-28           ÅRHUS    7   SOMETHING FISHY     0      0  21.98

[89 rows x 7 columns]
spår 0
Ålder 0
kön 0
dist 0
lopp_dist 0
streck efter med NaNs: 142
ta hand om outliers efter merge och matchningar innan predict
0    34477
1     3347
Name: plac, dtype: int64
0    26646
1    11178
Name: start, dtype: int64

In [258]:
df.plac.value_counts()

0    34477
1     3347
Name: plac, dtype: int64

In [259]:
df.spår.value_counts()

1     4281
2     4064
3     3964
4     3766
5     3452
6     3358
7     3021
9     2742
10    2515
8     2347
11    2194
12    1694
13     121
14     113
15     103
0       89
Name: spår, dtype: int64

In [260]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37824 entries, 0 to 37823
Data columns (total 65 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   datum      37824 non-null  datetime64[ns]
 1   avd        37824 non-null  int64
 2   häst       37824 non-null  object
 3   bana       37824 non-null  object
 4   dist       37824 non-null  int64
 5   h1_bana    37824 non-null  object
 6   h1_dat     37824 non-null  datetime64[ns]
 7   h1_dist    37824 non-null  float64
 8   h1_kmtid   37820 non-null  object
 9   h1_kusk    37824 non-null  object
 10  h1_odds    37771 non-null  object
 11  h1_plac    37817 non-null  object
 12  h1_pris    34738 non-null  float64
 13  h1_spår    35008 non-null  float64
 14  h2_bana    37824 non-null  object
 15  h2_dat     37824 non-null  datetime64[ns]
 16  h2_dist    37824 non-null  float64
 17  h2_kmtid   37821 non-null  object
 18  h2_kusk    37824 non-null  object
 19  h2_odds    37801 non-null  object
 20  h2_plac    37823 non-null  object
 21  h2_pris    34227 non-null  float64
 22  h2_spår    34611 non-null  float64
 23  h3_bana    37818 non-null  object
 24  h3_dat     37818 non-null  datetime64[ns]
 25  h3_dist    37818 non-null  float64
 26  h3_kmtid   37814 non-null  object
 27  h3_kusk    37818 non-null  object
 28  h3_odds    37793 non-null  object
 29  h3_plac    37817 non-null  object
 30  h3_pris    33832 non-null  float64
 31  h3_spår    34272 non-null  float64
 32  h4_bana    37796 non-null  object
 33  h4_dat     37796 non-null  datetime64[ns]
 34  h4_dist    37796 non-null  float64
 35  h4_kmtid   37792 non-null  object
 36  h4_kusk    37796 non-null  object
 37  h4_odds    37756 non-null  object
 38  h4_plac    37796 non-null  object
 39  h4_pris    33447 non-null  float64
 40  h4_spår    34001 non-null  float64
 41  h5_bana    37741 non-null  object
 42  h5_dat     37741 non-null  datetime64[ns]
 43  h5_dist    37741 non-null  float64
 44  h5_kmtid   37733 non-null  object
 45  h5_kusk    37741 non-null  object
 46  h5_odds    37696 non-null  object
 47  h5_plac    37739 non-null  object
 48  h5_pris    33095 non-null  float64
 49  h5_spår    33750 non-null  float64
 50  kr         37824 non-null  float64
 51  kusk       37824 non-null  object
 52  kön        37824 non-null  object
 53  lopp_dist  37824 non-null  float64
 54  plac       37824 non-null  int32
 55  podds      37824 non-null  float64
 56  pris       37824 non-null  float64
 57  spår       37824 non-null  int32
 58  start      37824 non-null  int64
 59  streck     37682 non-null  float64
 60  vodds      37824 non-null  float64
 61  ålder      37824 non-null  int64
 62  senast     37824 non-null  timedelta64[ns]
 63  timestamp  37824 non-null  timedelta64[ns]
 64  bins       37824 non-null  int64
dtypes: datetime64[ns](6), float64(21), int32(2), int64(5), object(29), timedelta64[ns](2)
memory usage: 18.5+ MB

In [261]:
mitt_datum = df.iloc[int(df.shape[0]/2)].datum
mitt_datum

Timestamp('2018-02-10 00:00:00')

### My idea is to learn following these steps
1. pick the n (~3) first avd from X_test_all into X_test and y_test
2. run catBoost
3. collect result-data
4. move 1 avd from test_all into X_train and y_train
5. start from 1

In [262]:
def get_rows_with_dates(df,n):
    # get the first rows in df with the n first dates
    dates = df.datum.unique()[:n]
    rows = df[df.datum=='ingen datum']   # empty with the same columns as df
    for d in dates:
        rows = pd.concat([rows,df[df.datum==d]], copy=True, ignore_index=True)
    print('rows',rows.shape)
    return rows

In [263]:
def move_rows_from_A_to_B(A,B,n):
    # select the n first datum in A
    move = get_rows_with_dates(A,n)
    a=A.iloc[move.shape[0]:] # remove the n first datum
    
    # add to the end of B
    b = pd.concat([B,move],ignore_index=True,copy=True)
    return a,b

In [264]:
def initsplit_my_data(df,mitt_datum):
    train=df[df.datum<=mitt_datum]
    test_all = df[df.datum>mitt_datum]

    print('Check that this is True',test_all.shape[0]+train.shape[0] == df.shape[0])
    train.shape,test_all.shape

    return train,test_all,

In [ ]:
# CatBoost fit
# save result
# move m (~1) rows from test_all to X_train
# Do it again date for date

In [514]:
def catfit(trainPool, testPool,auto=None,use_best=False,early=200,depth=2,learn_rate=0.04,iterations=250):
    
    from catboost import CatBoostClassifier
    model = CatBoostClassifier(  
        iterations=iterations,    
        depth=depth,   
        learning_rate=learn_rate,       
        auto_class_weights=auto ,
        eval_metric = 'Accuracy',
        loss_function = 'Logloss',
        early_stopping_rounds=early,
        random_state=2021,
        )
    if use_best:
        model.fit(trainPool,
        # cat_features= cat_features,
        eval_set=testPool,
        #auto_class_weights = auto,
        use_best_model=True,
        #plot=True,
        verbose = 100
        )
    else:            
        model.fit(trainPool,
        #auto_class_weights=auto,
        #eval_set=(X_test, y_test),
        #use_best_model=True,
        #plot=True,
        verbose = 300
        )
    
    return model

In [504]:
all_features = ['häst','kusk','bana','kön','lopp_dist','dist','kr','bins','podds','vodds','pris','spår','start','streck','timestamp','senast','ålder','plac']
cat_features = ['häst','kusk','bana','kön']
sel_feat = ['lopp_dist','dist','kr','bins','podds','vodds','timestamp','senast','pris','spår','start','streck','ålder']
add_features = ['lopp_dist','kr','timestamp','senast','pris','spår','start','streck','ålder']
sel_feat = cat_features + add_features

In [510]:
def remove_worst(worst_f,cat,add):
    wf=set(worst_f)
    
    while len(add)>0:
        if len(wf)==0:
            add.remove(add[0])
            return cat, add
            
        worst=max(wf, key=worst_f.count)
    
        if worst=='kön':
            print('remove kön från cat')
            cat.remove(worst)
            return cat,add
        if worst in cat:
            print('remove',worst,'från worst_f')
            while worst in worst_f:
                worst_f.remove(worst)
            wf=set(worst_f)
            continue

        print('remove',worst,'från add')
        add.remove(worst)   
        return cat, add

In [520]:
import time
cat_features = ['häst','kusk','bana','kön']
add_features = ['lopp_dist','dist','kr','timestamp','senast','pris','spår','start','streck','ålder']

from catboost import Pool
n=3 # antal veckor för varje test 
t0=time.time()
while len(add_features)>0:
   
    sel_feat = cat_features + add_features
    test_res = 'test_time'+str(30-len(sel_feat))+'.csv'

    train, test_all = initsplit_my_data(df,mitt_datum)
    X_test=test_all.loc[0:0]   # låna kolumnerna
    _,X_test = move_rows_from_A_to_B(test_all,X_test,n)

    worst_features=[]
    best_iteration=[]
    best_score=[]
    i=0
    t1 = time.time()
    while X_test.shape[0] > 0:
        t2=time.time()
        y_test = X_test.plac
        X_test.drop('plac',axis=1,inplace=True)

        y_train = train.plac
        X_train = train.drop('plac',axis=1)
        print(f'X_train {X_train.shape}, test_all {test_all.shape}, df {df.shape}')
        trainPool=Pool(X_train[sel_feat],y_train,cat_features=cat_features)
        testPool =Pool(X_test[sel_feat],y_test,cat_features=cat_features)
            
        model = catfit(trainPool,testPool,auto='Balanced',use_best=True,early=200,iterations=2000,depth=None,learn_rate=None)
        worst_features+=[model.get_feature_importance(prettified=True).iloc[-1,0]]

        best_iteration += [model.get_best_iteration()]
        best_score += [model.get_best_score()['validation']['Accuracy']]
        
        print(f'\niter {i+1} avg_score: {np.mean(best_score)}, freq. worst: {max(set(worst_features), key=worst_features.count)}')
        print(model.get_feature_importance(prettified=True).iloc[:3],'\nworst\n',model.get_feature_importance(prettified=True).iloc[-2:]) 

        # move one datum to X_train
        test_all,train = move_rows_from_A_to_B(test_all, train,1)
        
        X_test=test_all.loc[0:0]   # låna kolumnerna
        _,X_test = move_rows_from_A_to_B(test_all,X_test,n)
    
        print(f'\nX_test {X_test.shape} test_all {test_all.shape} train {train.shape} {test_all.shape[0]+train.shape[0]==len(df)} ')
        print(round(time.time()-t2,2),'sek')
        i+=1
        
    print(f'\nFinal avg_score: {sum(best_score)/len(best_score)}, freq. worst: {max(set(worst_feature), key=worst_feature.count)}')
    print(model.get_feature_importance(prettified=True))
    bs=pd.DataFrame({'bi': best_iteration,'bs': best_score})
    bs.to_csv(test_res, index=False)
    cat_features,add_features=remove_worst(worst_features,cat_features,add_features)
                        
    print(round(time.time()-t1,2),'sec  ENDED',test_res)

    break

print('ENDED PGM totalt',round(time.time()-t0,2),'sek')

, 65), df (37824, 65)
Learning rate set to 0.056856
0:	learn: 0.7441852	test: 0.7805633	best: 0.7805633 (0)	total: 103ms	remaining: 3m 25s
100:	learn: 0.7584145	test: 0.7232735	best: 0.7805633 (0)	total: 10.7s	remaining: 3m 22s
200:	learn: 0.7723304	test: 0.7395846	best: 0.7805633 (0)	total: 22s	remaining: 3m 17s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7805632866
bestIteration = 0

Shrink model to first 1 iterations.

iter 219 avg_score: 0.7704402390668967, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    83.305028
1      ålder    10.635775
2         kr     5.782497
worst
    Feature Id  Importances
12       spår          0.0
13      start          0.0
rows (77, 65)
rows (239, 65)

X_test (239, 65) test_all (1609, 65) train (36215, 65) True
22.431376695632935 sek
X_train (36215, 64), test_all (1609, 65), df (37824, 65)
Learning rate set to 0.056886
0:	learn: 0.7390241	test: 0.6902802	best: 0.6902802 (0)	total: 103ms	remaining: 3m 25s
100:	learn: 0.7594513	test: 0.6767421	best: 0.7425845 (1)	total: 11.1s	remaining: 3m 29s
200:	learn: 0.7720605	test: 0.6691582	best: 0.7425845 (1)	total: 22.6s	remaining: 3m 21s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7425845403
bestIteration = 1

Shrink model to first 2 iterations.

iter 220 avg_score: 0.7703136222541737, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    96.576295
1      ålder     1.663255
2       pris     0.948471
worst
    Feature Id  Importances
12       spår          0.0
13      start          0.0
rows (76, 65)
rows (247, 65)

X_test (247, 65) test_all (1533, 65) train (36291, 65) True
23.112181901931763 sek
X_train (36291, 64), test_all (1533, 65), df (37824, 65)
Learning rate set to 0.056916
0:	learn: 0.7372094	test: 0.7356509	best: 0.7356509 (0)	total: 103ms	remaining: 3m 26s
100:	learn: 0.7584620	test: 0.6803321	best: 0.7479030 (44)	total: 11.3s	remaining: 3m 32s
200:	learn: 0.7712705	test: 0.7103951	best: 0.7479030 (44)	total: 22.6s	remaining: 3m 22s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7479030334
bestIteration = 44

Shrink model to first 45 iterations.

iter 221 avg_score: 0.7702122168745561, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    82.071892
1       häst     4.908087
2       kusk     2.415075
worst
    Feature Id  Importances
12       dist     0.479714
13       spår     0.463332
rows (81, 65)
rows (250, 65)

X_test (250, 65) test_all (1452, 65) train (36372, 65) True
28.395421743392944 sek
X_train (36372, 64), test_all (1452, 65), df (37824, 65)
Learning rate set to 0.056947
0:	learn: 0.7373241	test: 0.6384885	best: 0.6384885 (0)	total: 86.6ms	remaining: 2m 53s
100:	learn: 0.7604598	test: 0.6005754	best: 0.6384885 (0)	total: 11.8s	remaining: 3m 41s
200:	learn: 0.7726505	test: 0.5841935	best: 0.6384885 (0)	total: 23s	remaining: 3m 26s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.6384884687
bestIteration = 0

Shrink model to first 1 iterations.

iter 222 avg_score: 0.7696188666575279, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    99.794695
1        kön     0.205305
2       häst     0.000000
worst
    Feature Id  Importances
12      start          0.0
13      ålder          0.0
rows (82, 65)
rows (248, 65)

X_test (248, 65) test_all (1370, 65) train (36454, 65) True
23.41634202003479 sek
X_train (36454, 64), test_all (1370, 65), df (37824, 65)
Learning rate set to 0.056979
0:	learn: 0.7462817	test: 0.6452169	best: 0.6452169 (0)	total: 102ms	remaining: 3m 24s
100:	learn: 0.7570828	test: 0.6587562	best: 0.6819830 (90)	total: 10.9s	remaining: 3m 24s
200:	learn: 0.7704718	test: 0.6864961	best: 0.7074663 (118)	total: 22.2s	remaining: 3m 18s
300:	learn: 0.7856717	test: 0.6655258	best: 0.7074663 (118)	total: 34.1s	remaining: 3m 12s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7074663327
bestIteration = 118

Shrink model to first 119 iterations.

iter 223 avg_score: 0.7693401557428449, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    57.144548
1       häst    11.058969
2       kusk     6.070761
worst
    Feature Id  Importances
12       pris     1.149293
13  lopp_dist     0.728216
rows (84, 65)
rows (241, 65)

X_test (241, 65) test_all (1286, 65) train (36538, 65) True
36.68987488746643 sek
X_train (36538, 64), test_all (1286, 65), df (37824, 65)
Learning rate set to 0.057011
0:	learn: 0.7371709	test: 0.6942667	best: 0.6942667 (0)	total: 71.2ms	remaining: 2m 22s
100:	learn: 0.7612337	test: 0.7165173	best: 0.7165173 (95)	total: 11.3s	remaining: 3m 33s
200:	learn: 0.7719378	test: 0.6975011	best: 0.7211025 (158)	total: 22.9s	remaining: 3m 24s
300:	learn: 0.7900747	test: 0.6791603	best: 0.7211025 (158)	total: 34.9s	remaining: 3m 17s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7211024627
bestIteration = 158

Shrink model to first 159 iterations.

iter 224 avg_score: 0.7691248088987634, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    53.230525
1       häst    10.475757
2       kusk     7.067111
worst
    Feature Id  Importances
12      start     1.147739
13       dist     1.093105
rows (84, 65)
rows (242, 65)

X_test (242, 65) test_all (1202, 65) train (36622, 65) True
42.21243858337402 sek
X_train (36622, 64), test_all (1202, 65), df (37824, 65)
Learning rate set to 0.057043
0:	learn: 0.7258070	test: 0.7365517	best: 0.7365517 (0)	total: 99.9ms	remaining: 3m 19s
100:	learn: 0.7579575	test: 0.7564591	best: 0.7800082 (25)	total: 11s	remaining: 3m 25s
200:	learn: 0.7700521	test: 0.7633206	best: 0.7800082 (25)	total: 22.6s	remaining: 3m 21s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7800082125
bestIteration = 25

Shrink model to first 26 iterations.

iter 225 avg_score: 0.7691731795814767, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    93.737237
1     senast     2.463423
2       bana     0.958454
worst
    Feature Id  Importances
12       pris          0.0
13      ålder          0.0
rows (80, 65)
rows (236, 65)

X_test (236, 65) test_all (1122, 65) train (36702, 65) True
25.85900378227234 sek
X_train (36702, 64), test_all (1122, 65), df (37824, 65)
Learning rate set to 0.057074
0:	learn: 0.7431115	test: 0.7769477	best: 0.7769477 (0)	total: 93.9ms	remaining: 3m 7s
100:	learn: 0.7576335	test: 0.7553895	best: 0.7961869 (46)	total: 11.4s	remaining: 3m 33s
200:	learn: 0.7705328	test: 0.7769477	best: 0.8054628 (132)	total: 22.8s	remaining: 3m 23s
300:	learn: 0.7889684	test: 0.7862236	best: 0.8101007 (273)	total: 34.9s	remaining: 3m 16s
400:	learn: 0.8042381	test: 0.7384693	best: 0.8101007 (273)	total: 47s	remaining: 3m 7s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8101007251
bestIteration = 273

Shrink model to first 274 iterations.

iter 226 avg_score: 0.7693542749156952, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    36.395578
1       häst    13.536915
2         kr    10.758178
worst
    Feature Id  Importances
12      start     1.486537
13       dist     1.466789
rows (77, 65)
rows (231, 65)

X_test (231, 65) test_all (1045, 65) train (36779, 65) True
56.4797899723053 sek
X_train (36779, 64), test_all (1045, 65), df (37824, 65)
Learning rate set to 0.057104
0:	learn: 0.7434473	test: 0.7485212	best: 0.7485212 (0)	total: 184ms	remaining: 6m 6s
100:	learn: 0.7603110	test: 0.7595585	best: 0.7820627 (19)	total: 11.6s	remaining: 3m 38s
200:	learn: 0.7740552	test: 0.7307095	best: 0.7820627 (19)	total: 23.5s	remaining: 3m 30s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7820626744
bestIteration = 19

Shrink model to first 20 iterations.

iter 227 avg_score: 0.7694102590545481, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    94.298302
1       spår     1.699174
2      ålder     1.141766
worst
    Feature Id  Importances
12     senast          0.0
13      start          0.0
rows (85, 65)
rows (215, 65)

X_test (215, 65) test_all (960, 65) train (36864, 65) True
26.144264698028564 sek
X_train (36864, 64), test_all (960, 65), df (37824, 65)
Learning rate set to 0.057136
0:	learn: 0.7430791	test: 0.7906328	best: 0.7906328 (0)	total: 36.3ms	remaining: 1m 12s
100:	learn: 0.7584807	test: 0.7275181	best: 0.7906328 (0)	total: 11s	remaining: 3m 27s
200:	learn: 0.7732267	test: 0.7672441	best: 0.7906328 (0)	total: 22.5s	remaining: 3m 21s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7906327524
bestIteration = 0

Shrink model to first 1 iterations.

iter 228 avg_score: 0.769503340165573, freq. worst: lopp_dist
  Feature Id  Importances
0     streck        100.0
1       häst          0.0
2       kusk          0.0
worst
    Feature Id  Importances
12      start          0.0
13      ålder          0.0
rows (74, 65)
rows (232, 65)

X_test (232, 65) test_all (886, 65) train (36938, 65) True
22.94130849838257 sek
X_train (36938, 64), test_all (886, 65), df (37824, 65)
Learning rate set to 0.057165
0:	learn: 0.7440348	test: 0.7250103	best: 0.7250103 (0)	total: 102ms	remaining: 3m 23s
100:	learn: 0.7584657	test: 0.6684018	best: 0.7390547 (3)	total: 11.2s	remaining: 3m 30s
200:	learn: 0.7717857	test: 0.6489830	best: 0.7390547 (3)	total: 22.5s	remaining: 3m 20s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7390547444
bestIteration = 3

Shrink model to first 4 iterations.

iter 229 avg_score: 0.7693703768651596, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    97.801889
1       spår     1.040068
2       pris     0.940837
worst
    Feature Id  Importances
12     senast          0.0
13      start          0.0
rows (72, 65)
rows (239, 65)

X_test (239, 65) test_all (814, 65) train (37010, 65) True
23.215975284576416 sek
X_train (37010, 64), test_all (814, 65), df (37824, 65)
Learning rate set to 0.057192
0:	learn: 0.7451430	test: 0.7485428	best: 0.7485428 (0)	total: 115ms	remaining: 3m 49s
100:	learn: 0.7580586	test: 0.7333697	best: 0.7784849 (78)	total: 11.4s	remaining: 3m 34s
200:	learn: 0.7709442	test: 0.7448859	best: 0.7784849 (78)	total: 23s	remaining: 3m 25s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7784849225
bestIteration = 78

Shrink model to first 79 iterations.

iter 230 avg_score: 0.7694100053246192, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    69.341663
1       häst     8.696125
2      ålder     5.298470
worst
    Feature Id  Importances
12       pris     0.313828
13       dist     0.296399
rows (69, 65)
rows (246, 65)

X_test (246, 65) test_all (745, 65) train (37079, 65) True
32.911155462265015 sek
X_train (37079, 64), test_all (745, 65), df (37824, 65)
Learning rate set to 0.057218
0:	learn: 0.7434442	test: 0.6967972	best: 0.6967972 (0)	total: 112ms	remaining: 3m 43s
100:	learn: 0.7567895	test: 0.7103994	best: 0.7223938 (58)	total: 11.7s	remaining: 3m 40s
200:	learn: 0.7716012	test: 0.6870699	best: 0.7223938 (58)	total: 23.1s	remaining: 3m 27s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7223937678
bestIteration = 58

Shrink model to first 59 iterations.

iter 231 avg_score: 0.7692064718287384, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    75.992672
1       häst     5.875083
2       kusk     3.788471
worst
    Feature Id  Importances
12  timestamp     0.648703
13  lopp_dist     0.424321
rows (91, 65)
rows (238, 65)

X_test (238, 65) test_all (654, 65) train (37170, 65) True
30.5620436668396 sek
X_train (37170, 64), test_all (654, 65), df (37824, 65)
Learning rate set to 0.057253
0:	learn: 0.7423510	test: 0.7318046	best: 0.7318046 (0)	total: 109ms	remaining: 3m 38s
100:	learn: 0.7575960	test: 0.7618150	best: 0.7618150 (91)	total: 10.9s	remaining: 3m 24s
200:	learn: 0.7701112	test: 0.7641235	best: 0.7664320 (153)	total: 22s	remaining: 3m 16s
300:	learn: 0.7874310	test: 0.7733574	best: 0.7733574 (277)	total: 33.7s	remaining: 3m 10s
400:	learn: 0.8001468	test: 0.7542098	best: 0.7733574 (277)	total: 45.2s	remaining: 3m
500:	learn: 0.8158405	test: 0.7726777	best: 0.7749862 (419)	total: 56.9s	remaining: 2m 50s
600:	learn: 0.8273609	test: 0.7343824	best: 0.7749862 (419)	total: 1m 8s	remaining: 2m 39s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7749862164
bestIteration = 419

Shrink model to first 420 iterations.

iter 232 avg_score: 0.7692313845209797, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    27.707451
1         kr    13.753277
2       häst    12.095596
worst
    Feature Id  Importances
12      start     1.045184
13  lopp_dist     1.008273
rows (79, 65)
rows (241, 65)

X_test (241, 65) test_all (575, 65) train (37249, 65) True
71.1935179233551 sek
X_train (37249, 64), test_all (575, 65), df (37824, 65)
Learning rate set to 0.057283
0:	learn: 0.7424852	test: 0.6772763	best: 0.6772763 (0)	total: 101ms	remaining: 3m 21s
100:	learn: 0.7574032	test: 0.7116656	best: 0.7139582 (90)	total: 11s	remaining: 3m 27s
200:	learn: 0.7722527	test: 0.7185434	best: 0.7208360 (165)	total: 22.3s	remaining: 3m 19s
300:	learn: 0.7868553	test: 0.7109906	best: 0.7231287 (241)	total: 34.1s	remaining: 3m 12s
400:	learn: 0.8017637	test: 0.7178684	best: 0.7231287 (241)	total: 46s	remaining: 3m 3s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7231286638
bestIteration = 241

Shrink model to first 242 iterations.

iter 233 avg_score: 0.7690335187666038, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    39.389433
1       häst    11.078941
2         kr     8.530933
worst
    Feature Id  Importances
12  lopp_dist     1.412271
13      start     1.366924
rows (76, 65)
rows (246, 65)

X_test (246, 65) test_all (499, 65) train (37325, 65) True
51.5335373878479 sek
X_train (37325, 64), test_all (499, 65), df (37824, 65)
Learning rate set to 0.057312
0:	learn: 0.7433789	test: 0.7661320	best: 0.7661320 (0)	total: 70.4ms	remaining: 2m 20s
100:	learn: 0.7557722	test: 0.7774657	best: 0.8007983 (74)	total: 11.1s	remaining: 3m 28s
200:	learn: 0.7707923	test: 0.7797325	best: 0.8007983 (74)	total: 22.4s	remaining: 3m 20s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8007983305
bestIteration = 74

Shrink model to first 75 iterations.

iter 234 avg_score: 0.7691692658254599, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    62.547060
1       häst    10.015805
2       kusk     5.817427
worst
    Feature Id  Importances
12        kön     0.764600
13  lopp_dist     0.332077
rows (83, 65)
rows (259, 65)

X_test (259, 65) test_all (416, 65) train (37408, 65) True
31.44439387321472 sek
X_train (37408, 64), test_all (416, 65), df (37824, 65)
Learning rate set to 0.057343
0:	learn: 0.7447150	test: 0.6988736	best: 0.6988736 (0)	total: 101ms	remaining: 3m 21s
100:	learn: 0.7576980	test: 0.7158386	best: 0.7296978 (80)	total: 11.1s	remaining: 3m 27s
200:	learn: 0.7708489	test: 0.6953742	best: 0.7407065 (139)	total: 22.4s	remaining: 3m 20s
300:	learn: 0.7890404	test: 0.6997777	best: 0.7407065 (139)	total: 34.1s	remaining: 3m 12s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7407064676
bestIteration = 139

Shrink model to first 140 iterations.

iter 235 avg_score: 0.7690481475350518, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    54.166186
1       häst     9.934706
2       kusk     6.932971
worst
    Feature Id  Importances
12      start     1.359331
13  lopp_dist     0.446525
rows (82, 65)
rows (252, 65)

X_test (252, 65) test_all (334, 65) train (37490, 65) True
39.20123815536499 sek
X_train (37490, 64), test_all (334, 65), df (37824, 65)
Learning rate set to 0.057374
0:	learn: 0.7425215	test: 0.6599584	best: 0.6599584 (0)	total: 106ms	remaining: 3m 31s
100:	learn: 0.7579318	test: 0.6615335	best: 0.6845555 (89)	total: 11.1s	remaining: 3m 28s
200:	learn: 0.7712446	test: 0.6496921	best: 0.6845555 (89)	total: 22.4s	remaining: 3m 20s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.6845554744
bestIteration = 89

Shrink model to first 90 iterations.

iter 236 avg_score: 0.7686901277336139, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    61.757955
1       häst    10.667588
2       kusk     7.099236
worst
    Feature Id  Importances
12      start     0.649005
13       dist     0.538388
rows (81, 65)
rows (253, 65)

X_test (253, 65) test_all (253, 65) train (37571, 65) True
33.2500216960907 sek
X_train (37571, 64), test_all (253, 65), df (37824, 65)
Learning rate set to 0.057405
0:	learn: 0.7433376	test: 0.6185761	best: 0.6185761 (0)	total: 106ms	remaining: 3m 31s
100:	learn: 0.7572572	test: 0.6208071	best: 0.6460094 (87)	total: 11s	remaining: 3m 26s
200:	learn: 0.7701387	test: 0.6341934	best: 0.6527026 (144)	total: 22.6s	remaining: 3m 22s
300:	learn: 0.7857624	test: 0.6498108	best: 0.6527026 (144)	total: 34.4s	remaining: 3m 13s
400:	learn: 0.8011617	test: 0.5735432	best: 0.6772442 (308)	total: 46.2s	remaining: 3m 4s
500:	learn: 0.8135900	test: 0.5824674	best: 0.6772442 (308)	total: 58s	remaining: 2m 53s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.6772441504
bestIteration = 308

Shrink model to first 309 iterations.

iter 237 avg_score: 0.7683042797278449, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    35.030823
1       häst    11.869750
2         kr    10.885994
worst
    Feature Id  Importances
12  lopp_dist     1.100680
13      start     0.841152
rows (96, 65)
rows (157, 65)

X_test (157, 65) test_all (157, 65) train (37667, 65) True
59.42236280441284 sek
X_train (37667, 64), test_all (157, 65), df (37824, 65)
Learning rate set to 0.057441
0:	learn: 0.7366238	test: 0.6187340	best: 0.6187340 (0)	total: 103ms	remaining: 3m 25s
100:	learn: 0.7592085	test: 0.6570326	best: 0.6570326 (95)	total: 10.7s	remaining: 3m 22s
200:	learn: 0.7737766	test: 0.6385754	best: 0.6779227 (185)	total: 21.8s	remaining: 3m 14s
300:	learn: 0.7881044	test: 0.6420570	best: 0.6779227 (185)	total: 33.4s	remaining: 3m 8s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.6779226879
bestIteration = 185

Shrink model to first 186 iterations.

iter 238 avg_score: 0.7679245251402604, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    51.516344
1       häst    10.202812
2       kusk     7.205948
worst
    Feature Id  Importances
12      start     1.048174
13  lopp_dist     1.012995
rows (75, 65)
rows (82, 65)

X_test (82, 65) test_all (82, 65) train (37742, 65) True
43.75719976425171 sek
X_train (37742, 64), test_all (82, 65), df (37824, 65)
Learning rate set to 0.057469
0:	learn: 0.7429597	test: 0.6607750	best: 0.6607750 (0)	total: 86ms	remaining: 2m 51s
100:	learn: 0.7548253	test: 0.7104011	best: 0.7104011 (89)	total: 10.8s	remaining: 3m 22s
200:	learn: 0.7711746	test: 0.7171992	best: 0.7171992 (187)	total: 22.2s	remaining: 3m 18s
300:	learn: 0.7872725	test: 0.6383413	best: 0.7171992 (187)	total: 33.9s	remaining: 3m 11s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.7171991842
bestIteration = 187

Shrink model to first 188 iterations.

iter 239 avg_score: 0.7677122852200164, freq. worst: lopp_dist
  Feature Id  Importances
0     streck    49.908767
1       häst    11.362723
2       kusk     8.491489
worst
    Feature Id  Importances
12       dist     1.273001
13  lopp_dist     1.215053
rows (82, 65)
rows (0, 65)

X_test (0, 65) test_all (0, 65) train (37824, 65) True
44.58571982383728 sek

Final avg_score: 0.7677122852200166, freq. worst: senast
   Feature Id  Importances
0      streck    49.908767
1        häst    11.362723
2        kusk     8.491489
3        spår     5.090502
4          kr     4.243049
5      senast     3.929555
6       ålder     3.495016
7        bana     3.359493
8         kön     2.113501
9       start     2.090381
10  timestamp     1.758213
11       pris     1.669258
12       dist     1.273001
13  lopp_dist     1.215053
remove lopp_dist från add
8496.99 sec  ENDED test_time16.csv
ENDED PGM totalt 8497.06 sek

In [560]:
# model.get_best_score()['validation']
# met=model.eval_metrics(testPool,['AUC','Accuracy','F1'])
np.mean(met['AUC']),np.mean(met['Accuracy']),np.mean(met['F1'])

(0.8252842686658315, 0.7456146574936, 0.754058306840742)

In [564]:
def results(fil):
    r=pd.read_csv(fil)
    print('\n',fil,'\n',r.describe().loc['mean','bs'])

results('test_time.csv')
results('test_time16.csv')
results('test_time17.csv')
results('test_time18.csv')
results('test_time19.csv')
results('test_time20.csv')
results('test_time21.csv')
results('test_time22.csv')
results('test_time23.csv')
results('test_time24.csv')
results('test_time25.csv')
results('test_time26.csv')

results('test_wtime.csv')
results('test_all.csv')    

results('test_small.csv')    

results('test_bins.csv')    
results('test_wbins.csv')    
results('test_streck.csv')   
results('test_wstreck.csv')

 test_time.csv
 0.8290144129283288

 test_time16.csv
 0.7677122852200166

 test_time17.csv
 0.8277424586829991

 test_time18.csv
 0.8282735120475199

 test_time19.csv
 0.8280944341113904

 test_time20.csv
 0.8282025417997456

 test_time21.csv
 0.8278655125336637

 test_time22.csv
 0.8284858672291422

 test_time23.csv
 0.8283224102272028

 test_time24.csv
 0.8278131121570628

 test_time25.csv
 0.8277167447248532

 test_time26.csv
 0.8273052787079769

 test_wtime.csv
 0.8282735120475199

 test_all.csv
 0.8373831096968835

 test_small.csv
 0.7053435497351221

 test_bins.csv
 0.836860084108841

 test_wbins.csv
 0.8361190945719769

 test_streck.csv
 0.8305874669055114

 test_wstreck.csv
 0.8299400747687696

In [362]:
print(model.get_feature_importance(prettified=True).iloc[:3],'\nworst\n',model.get_feature_importance(prettified=True).iloc[-2:])

  Feature Id  Importances
0     streck    74.503697
1       häst     8.149828
2       kusk     5.701039
worst
    Feature Id  Importances
11      start     0.583166
12       dist     0.384306

In [359]:
model.get_feature_importance(prettified=True)

   Feature Id  Importances
0      streck    74.503697
1        häst     8.149828
2        kusk     5.701039
3        bana     1.814385
4          kr     1.798336
5         kön     1.667706
6        spår     1.350540
7   timestamp     1.290839
8   lopp_dist     0.984482
9      senast     0.982821
10       pris     0.788855
11      start     0.583166
12       dist     0.384306

In [ ]:
# print(y_test.value_counts()[1]/y_test.value_counts()[0])
# print(y_train.value_counts()[1]/y_train.value_counts()[0])
print('Fundera på om jag skall använda class_weights')
print(y_train.value_counts())

In [ ]:
import pandas as pd
import numpy as np
import fixa_features as ff
import fixa_mer_features as ff2

df=pd.read_csv('mer_komplett.csv')
df.drop('tid',axis=1,inplace=True)

df=ff2.fixa_mer_features(df,hist=False)
df.lopp_dist=df.lopp_dist.astype('float')
df.plac = (df.plac==1)*1
print(df.plac.value_counts())  # CatBoost fungerar bättre med 0,1 än False, True
print(df.start.value_counts())

In [ ]:
from catboost import CatBoostClassifier, Pool
from catboost.utils import get_confusion_matrix 

all_features = ['häst','kusk','bana','kön','lopp_dist','dist','kr','streck','bins','podds','vodds','pris','spår','start','ålder','plac']
cat_features = ['häst','kusk','bana','kön']
#sel_feat = cat_features + ['lopp_dist','kr','bins','podds','vodds','pris','spår','start','streck','ålder']
sel_feat = cat_features + ['lopp_dist','kr','streck','bins','podds','vodds','pris','spår']

In [ ]:
train, test = initsplit_my_data(df,'2020-10-10')

trainPool = catb
testPool = Pool(data=test[sel_feat], label=test.plac, cat_features=cat_features)

print(f'train last {train.iloc[-1].datum} test first {test.iloc[0].datum}')

In [ ]:

model = catfit(trainPool, testPool, auto='Balanced',use_best=True,early=400,iterations=2000)
print(model.get_feature_importance(prettified=True))

In [ ]:
print(get_confusion_matrix(model,data=testPool))
eval = model.eval_metrics(testPool,['Accuracy','F1','Precision','Recall'])
print(f"Accuracy={round(np.mean(eval['Accuracy']),2)}, F1={round(np.mean(eval['F1']),2)}, Precision={round(np.mean(eval['Precision']),2)},Recall {round(np.mean(eval['Recall']),2)}")

In [ ]:
# best_iteration += [model.get_best_iteration()]
print(model.get_best_score())
pred=model.predict(testPool)

In [ ]:
model.get_feature_importance(prettified=True)